# Stage 0: Base image for building the app
FROM node:20.11.0-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# Stage 1: Build the app
FROM base AS build
ARG BUILD_DATABASE_URL
ENV DATABASE_URL $BUILD_DATABASE_URL
ARG VITE_API_URL
ENV VITE_API_URL $VITE_API_URL
WORKDIR /app
COPY . .

# Install dependencies
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run --filter "@icewar/prisma" generate
RUN pnpm run --filter "@icewar/prisma" build

# Build the app for production
RUN pnpm run --filter "@icewar/frontend" build

# Stage 2: Serve the app using nginx
FROM nginx:alpine

# Copy the built React app from the build stage
COPY --from=build /app/frontend/dist /usr/share/nginx/html

# Expose the default nginx port
EXPOSE 80
ENV NODE_ENV production

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
