services:
  crawler:
    build: 
      context: .
      dockerfile: ./crawler/Dockerfile 
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}

  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile 
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - crawler
    environment:
      CRAWLER_URL: ${CRAWLER_URL}

