services:

  crawler:
    build: 
      context: .
      dockerfile: ./crawler/Dockerfile 
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}

  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        BUILD_DATABASE_URL: ${BUILD_DATABASE_URL}
        VITE_API_URL: ${VITE_API_URL}

    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - crawler
    environment:
      VITE_API_URL: ${VITE_API_URL}


