services:
  db:
    image: postgres:16.3
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  crawler:
    build: 
      context: .
      # additional_contexts:
      #   - base=.
        # - app=/scraper
      dockerfile: ./scraper/Dockerfile 
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  db_data:
