services:
  db:
    image: postgres:16.3
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./scraper/.env
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  crawler:
    build: 
      context: .
      dockerfile: ./crawler/Dockerfile
      # dockerfile: ./Dockerfile 
 
    # command: ["tail", "-f", "/dev/null"]
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./crawler/.env
    # environment:
    #   DATABASE_URL: ${DATABASE_URL}

  # frontend:
  #   build: 
  #     context: .
  #     dockerfile: ./frontend/Dockerfile 
  #   restart: unless-stopped
  #   ports:
  #     - "3001:80"
  #   depends_on:
  #     - crawler
  #   env_file:
  #     - ./frontend/.env
  #   # environment:
  #   #   CRAWLER_URL: ${CRAWLER_URL}
  #     # VITE_API_URL: ${VITE_API_URL}

volumes:
  db_data:
