services:
  crawler:
    build: 
      context: .

      dockerfile: ./scraper/Dockerfile 
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}

  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile 
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - crawler
    environment:
      CRAWLER_URL: ${CRAWLER_URL}

