FROM node:20.11.0-alpine AS base
WORKDIR /app
RUN corepack enable

FROM base AS build
WORKDIR /app
RUN corepack enable
COPY . .
RUN pnpm install 
RUN ls -la /app/node_modules/
RUN pnpm 
RUN pnpm run prisma
RUN pnpm run --filter "@icewar/scraper" build

# Final image creation
FROM node:20.11.0-alpine AS production

ENV ADDRESS=0.0.0.0 PORT=3000
ENV NODE_ENV=production

WORKDIR /app
COPY --from=build /app/dist .
COPY --from=build /app/node_modules .

CMD ["node", "dist/index.js"]