name: Push to Azure Container Registry
on:
    push:
        branches:
        - main

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure Registry Login
        run: az acr login --name ${{ vars.ACR_REGISTRY }}

      - name: Build and push
        run: |
          docker build . -t ${{ vars.ACR_REGISTRY }}.azurecr.io/crawler:latest
          docker push ${{ vars.ACR_REGISTRY }}.azurecr.io/crawler:latest